# Generated by Django 3.2 on 2021-04-15 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_user', models.CharField(max_length=32)),
                ('receive', models.CharField(max_length=32)),
                ('content', models.TextField()),
                ('category', models.SmallIntegerField(default=0)),
                ('email_title', models.CharField(max_length=128)),
                ('datatime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '邮件',
                'verbose_name_plural': '邮件',
                'db_table': 'emailcontent',
            },
        ),
        migrations.CreateModel(
            name='EmailUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'emailuser',
            },
        ),
    ]
